version: '3.8'

volumes:
  mydb:
  phpvol:

services:
  db:
    image: mysql
    container_name: db1
    environment:
      - MYSQL_ROOT_PASSWORD=pass
      - MYSQL_DATABASE=scholarevents
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - mydb:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adm1
    ports:
      - 8081:8080
    depends_on:
      - db

  web:
    image: web
    container_name: web1
    ports:
      - 8080:80
    depends_on:
      - db
    build: .
    volumes:
      - phpvol:/var/www/html